name: Batch Cron

on:
    schedule:
        - cron: '*/1 * * * *'
    workflow_dispatch:

jobs:
    batch-cron:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Batch Article
              run: |
                  curl -X 'POST' \
                    'https://api.fewletter.site/batch/article' \
                    -H 'accept: application/json' \
                    -H 'Content-Type: application/json'
