name: Integration Test

on:
    pull_request:
        types: [opened]
        branches: [ "main", "dev" ]
    workflow_dispatch:

permissions:
    contents: read

env:
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

    setup-java:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

    jooq-codegen:
        runs-on: ubuntu-latest
        needs: setup-java
        steps:
            - name: Jooq Code Generation
              run: ./gradlew --info jooqCodegenAll

    test:
        runs-on: ubuntu-latest
        needs: jooq-codegen
        steps:
            - name: Test with Gradle
              run: ./gradlew --info test
