name: Terraform IAC

on:
  push:
    branches:
      - infra/main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      working-directory: ./infra/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ${{ env.working-directory }}
        run: terraform init

      - name: Terraform Format
        working-directory: ${{ env.working-directory }}
        run: terraform fmt -check

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.3.0
          tf_actions_subcommand: "plan"
          tf_actions_comment: "true"
          tf_actions_working_dir: ${{ env.working-directory }}
          tf_actions_vars: |
            aws_root_arn=${{ secrets.AWS_ROOT_ARN }}
            aws_access_key=${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key=${{ secrets.AWS_SECRET_SECRET_KEY }}
            aws_rds_password=${{ secrets.AWS_RDS_PASSWORD }}
            fe_origin=${{ secrets.FE_ORIGIN }}
            email_username=${{ secrets.EMAIL_USERNAME }}
            email_password=${{ secrets.EMAIL_PASSWORD }}
            webhook_discord=${{ secrets.WEBHOOK_DISCORD }}

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.3.0
          tf_actions_subcommand: "apply"
          tf_actions_comment: "true"
          tf_actions_working_dir: ${{ env.working-directory }}
          tf_actions_vars: |
            aws_root_arn=${{ secrets.AWS_ROOT_ARN }}
            aws_access_key=${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key=${{ secrets.AWS_SECRET_SECRET_KEY }}
            aws_rds_password=${{ secrets.AWS_RDS_PASSWORD }}
            fe_origin=${{ secrets.FE_ORIGIN }}
            email_username=${{ secrets.EMAIL_USERNAME }}
            email_password=${{ secrets.EMAIL_PASSWORD }}
            webhook_discord=${{ secrets.WEBHOOK_DISCORD }}
